### ISSUE TITLE
add vocab terms

### ISSUE THREAD

**Issue by pamelajean** [WGBH/PBCore_2.1#22]
hello!
to accommodate film sources may i suggest adding the term "1.33:1" to the controlled vocab for
pbcoreEssenceTrackAspectRatio
http://metadataregistry.org/concept/list/vocabulary_id/129.html

and may we add "Access Copy: Edited" to the controlled vocab for 
instantiationGenerations
http://metadataregistry.org/concept/list/page/5/vocabulary_id/147.html

(or since the term "Copy: access" already exists should it be "Copy: edited access"?)

and may we add the following to the controlled vocab for instantiationPhysical
http://metadataregistry.org/concept/list/page/1/vocabulary_id/145.html
Film: 22mm
Filmstrip
Glass instantaneous disc (or just "Instananeous disc")
Transcription disc
VHS-C

and to accommodate some of our non-a/v objects:
Broadside (notice) (or just "Broadside")
Ephemera
Pamphlet
Photograph ("Photographic negative" and "Photographic positive" are there but we may not know the source of a digital file unless it's in the supplied metadata so we prefer a more general term)

thanks,
pamela
california audiovisual preservation project (cavpp)

**Comment by johnnypass** [comment]
My thoughts on the two disc suggestions. 

If I had, as an example, a 16-inch lacquer transcription disc, I could currently describe it in PBcore as a 1. lacquer disc 2. transcription disc 3. record 4. instantaneous disc.

It seems there is a problem in conflating the material of a disc and the process with which the disc was created. For example, an instantaneous disc could be a lacquer disc or an uncoated aluminum disc or even a vinyl disc. Transcription discs can be pressings but they can also be instantaneous discs, All lacquer discs are instantaneous, but shellac discs can only be pressings. 

And the term 'record' doesn't seem very help. 

This is all to say that it might be better to stick with one way of describing a disc, either by its material (shellac, vinyl, aluminum, lacquer, etc...) or its process (instantaneous, pressing). Although that may be difficult because I think part of the problem is that PBCore has no element for 'material', the way it does for say 'dimension'. 

IASA has these suggestions. 

http://www.iasa-web.org/cataloguing-rules/5b-extent-specific-material-designation-type-format

sound cartridge
sound cassette
sound cylinder
sound disc
sound tape reel
sound wire reel
sound track film reel

**Comment by rfraimow** [comment]
Writing to resolve these suggestions:

We are no longer supporting the pbcoreEssenceTrackAspectRatio controlled vocabulary, since this can be automatically supplied by tools such as MediaInfo. 

22m film has been added to the instantiationPhysical: Film list.
VHS-C is included as a subtype of VHS on the instantiationPhysical: Video list.
Glass disc is included as a subtype of 'lacquer disc' on the instantiationPhysical: Audio list.
Transcription disc has been added to instantiationGenerations (to make it repeatable with the edited terms vinyl record, shellac disc, lacquer disc, and aluminum disc.)

After several discussions, the decision was made not to support non-a/v materials on the PBCore audio and video-specific controlled vocabulary lists, but to recommend outside vocabularies for these. 

After discussion, the group decided not to include Copy: access (edited) to the instantiationGenerations list.
